# 服务器
server:
  port: 8071
  session:
    timeout: 1800  # 30 分钟

#注册中心
eureka:
  server:
    enableSelfPreservation: false       # 设为false，关闭自我保护
    evictionIntervalTimerInMs: 1000     # 清理间隔（单位毫秒，默认是60*1000）
  instance:
        instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}
        prefer-ip-address: true
        hostname: ${spring.cloud.client.ipAddress}
  client:
    serviceUrl:
      # defaultZone: http://admin:123456@192.168.1.128:9205/eureka/,http://admin:123456@192.168.1.129:9205/eureka/
      defaultZone: http://admin:123456@127.0.0.1:9205/eureka/

# 添加用户认证
security:
    basic:
      enabled: true       # 开启基于HTTP basic的认证
    user:
      name: admin         # 配置登录的账号
      password: 123456    # 配置登录的密码是password123

# 数据库
druid:
  url: jdbc:mysql://127.0.0.1:3306/iot?useUnicode=true&rewriteBatchedStatements=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
  userName: root
  password: 123456

spring:
# kafka
  kafka:
    # bootstrap-servers: 192.168.1.128:9092,192.168.1.129:9092
    #单机版用这个地址
    bootstrap-servers: 127.0.0.1:9092
    producer:
      batch-size: 26384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
    consumer:
      group-id: consumer-prorps
      auto-offset-reset: latest
      session.timeout.ms: 60000
      enable-auto-commit: false
      auto-commit-interval: 1000
      max-poll-records: 600
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
    #自定义 concurrency 为通道数，需要kafka分区配合使用。实例数量*concurrency=分区数量。需要用命为property主题增加分区
      concurrency: 10
      batch: true

#  mongodb设置
  data:
    mongodb:
      # uri: mongodb://192.168.1.127:27017,192.168.1.128:27017,192.168.1.129:27017
      uri: mongodb://127.0.0.1:27017
      database: t9
# redis设置
  redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
      database: 0
      timeout: 20000
#     cluster:
#       nodes: 192.168.15.83:7001,192.168.15.83:7002,192.168.15.83:7003
#       max-redirects: 6
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
        max-wait: -1
kafkaConcurrency: 10

#部署方式
module: 
  deploymentType: single
  # deploymentType: cluster
  #模块组别，al,rdp,ej,em,etl,config,facade,his。模块应用需要加载的服务，多个角色用逗号分隔
  group: #al,rdp,ej,em,etl,config,facade,his
  #模块名称，每个部署的微服务都不一样 
  name: dcom
  snowFlakeSetting: 0-1
  enablemongo: true
  enablekafka: true
  mPointPartitionNum: 10 #kafka分区数量，结合配置
  bPointPartitionNum: 10
  etlPointPartitionNum: 10
  vipAddr:  #双机热备时，vip地址，只有当deploymentType=single时有用
  alChangeFilter: true #接入层值变化过滤
  project: deviceCloud #项目定制切换开关，deviceCloud 设备云


# DebugInterceptor
appDebug:
  debug: true

# SnowFlake 发号器 . 格式为 0-0 ，前面数字是 本实例启动的序号。 后面的数字是 整个dataCenter系统启动的序号。
#*******一般来说，启动多个使用snowflake 实例，只需要更改前面的序号。 两个参数的取值范围是 0-31 的整数******
snowFlakeParam:
  snowFlakeSetting: 0-1

# 系统管理模块的一些配置
systemSetting:
  # 登录前查应用配置信息，需要固化这个TenantId
  tenantId: 1
  logo:
    appLogoPath: /opt/data/files/images/appLogo
    loginLogoPath: /opt/data/files/images/loginLogo

# 动环系统数据推送    
pushDataUri: 

#nginx-rtmp应用url
nginx-rtmp-url: rtmp://ip:1935/mytv

# netty 门禁客户端
isOpenNettyClient: false
nettyClientIP: 127.0.0.1
nettyClientPort: 60006

# 门禁类型 当前平台接入过的门禁设备类型有:
#     Syris(玺瑞门禁)  Wiegand(微耕门禁) Cqaccess(卡瑞门禁)  Zokin(拙进门禁) Zkteco(中控门禁)  Hikvision(海康门禁)
accessDoorType: ""

# 海康门禁相关配置项
apiServerIp: 192.168.233.2  # 该配置项用于海康安防平台回调 serverIp为DCOM平台部署ip
artemisConfigHost: 192.168.233.17 # 该配置项为海康安防平台部署ip
artemisConfigPort: 80 # 该配置项为海康安防平台 API调用端口 默认为80
artemisConfigRequestProtocol: http:// # 该配置项为海康安防平台 API请求协议 默认为http://
artemisConfigAppKey: 29570907 # 该配置项为海康安防平台 API请求密钥
artemisConfigAppSecret: DeFkTm6RXvJDz5qYViKl # 该配置项为海康安防平台 API请求密匙

# 中控门禁相关配置项(供电局中控门禁采用Http方式进行调用)
zkAccessDoorIp: 192.168.6.2
zkAccessDoorPort: 8071


#视频
video:
  app: video
  port: 1935
  path: /live
  timeout: 30

#华为IVS账号密码
ivs:
  account: Admin
  password: HUAwei123
  
#是否已部署华为esdk服务 1:是  0:否
esdk:
  enabled: 0
  keepAliveInterval: 40
  loginInterval: 60
  
#海康摄像头
hik:
  expand: streamform=rtp
  
#成都人行定制
cdrh:
  enable: true
  serverip: 192.168.1.100
  serverport: 8888
  loginuser: system
  loginpwd: 123
  loncomip: 192.168.1.200
  dcimsip: 192.168.1.1
  dcimsport: 9996
  vedioip: 192.168.5.25
  vedioport: 8088

printer:
  ip: 127.0.0.1
  port: 1234
